// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     payment.avsc
 */
package model

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type Payment struct {
	Id string `json:"id"`

	Description string `json:"description"`
}

const PaymentAvroCRC64Fingerprint = "\xbf\xc1\x9dwdpS\xdb"

func NewPayment() Payment {
	r := Payment{}
	return r
}

func DeserializePayment(r io.Reader) (Payment, error) {
	t := NewPayment()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializePaymentFromSchema(r io.Reader, schema string) (Payment, error) {
	t := NewPayment()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writePayment(r Payment, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Id, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Description, w)
	if err != nil {
		return err
	}
	return err
}

func (r Payment) Serialize(w io.Writer) error {
	return writePayment(r, w)
}

func (r Payment) Schema() string {
	return "{\"fields\":[{\"comment\":\"UUID of payment\",\"name\":\"id\",\"type\":\"string\"},{\"comment\":\"Payment description\",\"name\":\"description\",\"type\":\"string\"}],\"name\":\"com.saneetbhella.schemas.Payment\",\"type\":\"record\"}"
}

func (r Payment) SchemaName() string {
	return "com.saneetbhella.schemas.Payment"
}

func (_ Payment) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ Payment) SetInt(v int32)       { panic("Unsupported operation") }
func (_ Payment) SetLong(v int64)      { panic("Unsupported operation") }
func (_ Payment) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ Payment) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ Payment) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ Payment) SetString(v string)   { panic("Unsupported operation") }
func (_ Payment) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Payment) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Id}

		return w

	case 1:
		w := types.String{Target: &r.Description}

		return w

	}
	panic("Unknown field index")
}

func (r *Payment) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *Payment) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ Payment) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ Payment) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ Payment) HintSize(int)                     { panic("Unsupported operation") }
func (_ Payment) Finalize()                        {}

func (_ Payment) AvroCRC64Fingerprint() []byte {
	return []byte(PaymentAvroCRC64Fingerprint)
}

func (r Payment) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["id"], err = json.Marshal(r.Id)
	if err != nil {
		return nil, err
	}
	output["description"], err = json.Marshal(r.Description)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *Payment) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["description"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Description); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for description")
	}
	return nil
}
